<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="demo_mashup" targetNamespace="http://www.convertigo.com/convertigo/projects/demo_mashup" xmlns:demo_mashup_ns="http://www.convertigo.com/convertigo/projects/demo_mashup" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/">
  <wsdl:types>
    <xsd:schema targetNamespace="http://www.convertigo.com/convertigo/projects/demo_mashup"><xsd:include schemaLocation="demo_mashup.xsd"/></xsd:schema>
  </wsdl:types>
  <wsdl:portType name="demo_mashupPortType">
  </wsdl:portType>
  <wsdl:binding name="demo_mashupSOAPBinding" type="demo_mashup_ns:demo_mashupPortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
  </wsdl:binding>
  <wsdl:service name="demo_mashup">
    <wsdl:port name="demo_mashupSOAP" binding="demo_mashup_ns:demo_mashupSOAPBinding">
      <soap:address location="http://localhost:18080/convertigo/projects/demo_mashup/.wsl"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
