<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="template_interactionHub" targetNamespace="http://www.convertigo.com/convertigo/projects/template_interactionHub" xmlns:template_interactionHub_ns="http://www.convertigo.com/convertigo/projects/template_interactionHub" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/">
  <wsdl:types>
    <xsd:schema targetNamespace="http://www.convertigo.com/convertigo/projects/template_interactionHub"><xsd:include schemaLocation="template_interactionHub.xsd"/></xsd:schema>
  </wsdl:types>
  <wsdl:portType name="template_interactionHubPortType">
  </wsdl:portType>
  <wsdl:binding name="template_interactionHubSOAPBinding" type="template_interactionHub_ns:template_interactionHubPortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
  </wsdl:binding>
  <wsdl:service name="template_interactionHub">
    <wsdl:port name="template_interactionHubSOAP" binding="template_interactionHub_ns:template_interactionHubSOAPBinding">
      <soap:address location="http://localhost:18080/convertigo/projects/template_interactionHub/.wsl"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
