<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="template_SQL" targetNamespace="http://www.convertigo.com/convertigo/projects/template_SQL" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:template_SQL_ns="http://www.convertigo.com/convertigo/projects/template_SQL" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/">
  <wsdl:types>
    <xsd:schema targetNamespace="http://www.convertigo.com/convertigo/projects/template_SQL"><xsd:include schemaLocation="template_SQL.xsd"/></xsd:schema>
  </wsdl:types>
  <wsdl:portType name="template_SQLPortType">
  </wsdl:portType>
  <wsdl:binding name="template_SQLSOAPBinding" type="template_SQL_ns:template_SQLPortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
  </wsdl:binding>
  <wsdl:service name="template_SQL">
    <wsdl:port name="template_SQLSOAP" binding="template_SQL_ns:template_SQLSOAPBinding">
      <soap:address location="http://localhost:18080/convertigo/projects/template_SQL/.wsl"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
