<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="template_SQL" targetNamespace="http://www.convertigo.com/convertigo/projects/template_SQL" xmlns:template_SQL_ns="http://www.convertigo.com/convertigo/projects/template_SQL" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:types>
    <xsd:schema targetNamespace="http://www.convertigo.com/convertigo/projects/template_SQL"><xsd:include schemaLocation="template_SQL.xsd"/></xsd:schema>
  </wsdl:types>
  <wsdl:message name="SqlConnector__DefaultTransactionRequest">
    <wsdl:part name="parameters" element="template_SQL_ns:SqlConnector__DefaultTransaction">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="SqlConnector__DefaultTransactionResponse">
    <wsdl:part name="parameters" element="template_SQL_ns:SqlConnector__DefaultTransactionResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="template_SQLPortType">
    <wsdl:operation name="SqlConnector__DefaultTransaction">
<wsdl:documentation><![CDATA[]]></wsdl:documentation>
      <wsdl:input message="template_SQL_ns:SqlConnector__DefaultTransactionRequest">
    </wsdl:input>
      <wsdl:output message="template_SQL_ns:SqlConnector__DefaultTransactionResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="template_SQLSOAPBinding" type="template_SQL_ns:template_SQLPortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="SqlConnector__DefaultTransaction">
<wsdl:documentation><![CDATA[]]></wsdl:documentation>
      <soap:operation soapAction="template_SQL?void__Default_transaction"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="template_SQL">
    <wsdl:port name="template_SQLSOAP" binding="template_SQL_ns:template_SQLSOAPBinding">
      <soap:address location="http://localhost:18080/convertigo/projects/template_SQL/.wsl"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
