<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="sample_documentation_CMC" targetNamespace="http://www.convertigo.com/convertigo/projects/sample_documentation_CMC" xmlns:sample_documentation_CMC_ns="http://www.convertigo.com/convertigo/projects/sample_documentation_CMC" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/">
  <wsdl:types>
    <xsd:schema targetNamespace="http://www.convertigo.com/convertigo/projects/sample_documentation_CMC"><xsd:include schemaLocation="sample_documentation_CMC.xsd"/></xsd:schema>
  </wsdl:types>
  <wsdl:portType name="sample_documentation_CMCPortType">
  </wsdl:portType>
  <wsdl:binding name="sample_documentation_CMCSOAPBinding" type="sample_documentation_CMC_ns:sample_documentation_CMCPortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
  </wsdl:binding>
  <wsdl:service name="sample_documentation_CMC">
    <wsdl:port name="sample_documentation_CMCSOAP" binding="sample_documentation_CMC_ns:sample_documentation_CMCSOAPBinding">
      <soap:address location="http://localhost:18080/convertigo/projects/sample_documentation_CMC/.wsl"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
