<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="sampleMobileUsDirectoryDemo" targetNamespace="http://www.convertigo.com/convertigo/projects/sampleMobileUsDirectoryDemo" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:sampleMobileUsDirectoryDemo_ns="http://www.convertigo.com/convertigo/projects/sampleMobileUsDirectoryDemo" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:types>
    <xsd:schema targetNamespace="http://www.convertigo.com/convertigo/projects/sampleMobileUsDirectoryDemo"><xsd:include schemaLocation="sampleMobileUsDirectoryDemo.xsd"/></xsd:schema>
  </wsdl:types>
  <wsdl:portType name="sampleMobileUsDirectoryDemoPortType">
  </wsdl:portType>
  <wsdl:binding name="sampleMobileUsDirectoryDemoSOAPBinding" type="sampleMobileUsDirectoryDemo_ns:sampleMobileUsDirectoryDemoPortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
  </wsdl:binding>
  <wsdl:service name="sampleMobileUsDirectoryDemo">
    <wsdl:port name="sampleMobileUsDirectoryDemoSOAP" binding="sampleMobileUsDirectoryDemo_ns:sampleMobileUsDirectoryDemoSOAPBinding">
      <soap:address location="http://localhost:18080/convertigo/projects/sampleMobileUsDirectoryDemo/.wsl"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
