<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="crawlingProjectTemplate" targetNamespace="http://www.convertigo.com/convertigo/projects/crawlingProjectTemplate" xmlns:crawlingProjectTemplate_ns="http://www.convertigo.com/convertigo/projects/crawlingProjectTemplate" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/">
  <wsdl:types>
    <xsd:schema targetNamespace="http://www.convertigo.com/convertigo/projects/crawlingProjectTemplate"><xsd:include schemaLocation="crawlingProjectTemplate.xsd"/></xsd:schema>
  </wsdl:types>
  <wsdl:portType name="crawlingProjectTemplatePortType">
  </wsdl:portType>
  <wsdl:binding name="crawlingProjectTemplateSOAPBinding" type="crawlingProjectTemplate_ns:crawlingProjectTemplatePortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
  </wsdl:binding>
  <wsdl:service name="crawlingProjectTemplate">
    <wsdl:port name="crawlingProjectTemplateSOAP" binding="crawlingProjectTemplate_ns:crawlingProjectTemplateSOAPBinding">
      <soap:address location="http://localhost:18080/convertigo/projects/crawlingProjectTemplate/.wsl"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
