<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="template_javelinDKU" targetNamespace="http://www.convertigo.com/convertigo/projects/template_javelinDKU" xmlns:template_javelinDKU_ns="http://www.convertigo.com/convertigo/projects/template_javelinDKU" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/">
  <wsdl:types>
    <xsd:schema targetNamespace="http://www.convertigo.com/convertigo/projects/template_javelinDKU"><xsd:include schemaLocation="template_javelinDKU.xsd"/></xsd:schema>
  </wsdl:types>
  <wsdl:portType name="template_javelinDKUPortType">
  </wsdl:portType>
  <wsdl:binding name="template_javelinDKUSOAPBinding" type="template_javelinDKU_ns:template_javelinDKUPortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
  </wsdl:binding>
  <wsdl:service name="template_javelinDKU">
    <wsdl:port name="template_javelinDKUSOAP" binding="template_javelinDKU_ns:template_javelinDKUSOAPBinding">
      <soap:address location="http://localhost:18080/convertigo/projects/template_javelinDKU/.wsl"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
