<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="sampleMobileWebToPdf" targetNamespace="http://www.convertigo.com/convertigo/projects/sampleMobileWebToPdf" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:sampleMobileWebToPdf_ns="http://www.convertigo.com/convertigo/projects/sampleMobileWebToPdf" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/">
  <wsdl:types>
    <xsd:schema targetNamespace="http://www.convertigo.com/convertigo/projects/sampleMobileWebToPdf"><xsd:include schemaLocation="sampleMobileWebToPdf.xsd"/></xsd:schema>
  </wsdl:types>
  <wsdl:portType name="sampleMobileWebToPdfPortType">
  </wsdl:portType>
  <wsdl:binding name="sampleMobileWebToPdfSOAPBinding" type="sampleMobileWebToPdf_ns:sampleMobileWebToPdfPortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
  </wsdl:binding>
  <wsdl:service name="sampleMobileWebToPdf">
    <wsdl:port name="sampleMobileWebToPdfSOAP" binding="sampleMobileWebToPdf_ns:sampleMobileWebToPdfSOAPBinding">
      <soap:address location="http://localhost:18080/convertigo/projects/sampleMobileWebToPdf/.wsl"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
