<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="template_mobileJQueryMobile" targetNamespace="http://www.convertigo.com/convertigo/projects/template_mobileJQueryMobile" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:template_mobileJQueryMobile_ns="http://www.convertigo.com/convertigo/projects/template_mobileJQueryMobile" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/">
  <wsdl:types>
    <xsd:schema targetNamespace="http://www.convertigo.com/convertigo/projects/template_mobileJQueryMobile"><xsd:include schemaLocation="template_mobileJQueryMobile.xsd"/></xsd:schema>
  </wsdl:types>
  <wsdl:portType name="template_mobileJQueryMobilePortType">
  </wsdl:portType>
  <wsdl:binding name="template_mobileJQueryMobileSOAPBinding" type="template_mobileJQueryMobile_ns:template_mobileJQueryMobilePortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
  </wsdl:binding>
  <wsdl:service name="template_mobileJQueryMobile">
    <wsdl:port name="template_mobileJQueryMobileSOAP" binding="template_mobileJQueryMobile_ns:template_mobileJQueryMobileSOAPBinding">
      <soap:address location="http://localhost:18080/convertigo/projects/template_mobileJQueryMobile/.wsl"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
