<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="sample_refManual_steps" targetNamespace="http://www.convertigo.com/convertigo/projects/sample_refManual_steps" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:sample_refManual_steps_ns="http://www.convertigo.com/convertigo/projects/sample_refManual_steps" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/">
  <wsdl:types>
    <xsd:schema targetNamespace="http://www.convertigo.com/convertigo/projects/sample_refManual_steps"><xsd:include schemaLocation="sample_refManual_steps.xsd"/></xsd:schema>
  </wsdl:types>
  <wsdl:portType name="sample_refManual_stepsPortType">
  </wsdl:portType>
  <wsdl:binding name="sample_refManual_stepsSOAPBinding" type="sample_refManual_steps_ns:sample_refManual_stepsPortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
  </wsdl:binding>
  <wsdl:service name="sample_refManual_steps">
    <wsdl:port name="sample_refManual_stepsSOAP" binding="sample_refManual_steps_ns:sample_refManual_stepsSOAPBinding">
      <soap:address location="http://localhost:18080/convertigo/projects/sample_refManual_steps/.wsl"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
