<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="template_FLEX" targetNamespace="http://www.convertigo.com/convertigo/projects/template_FLEX" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:template_FLEX_ns="http://www.convertigo.com/convertigo/projects/template_FLEX" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/">
  <wsdl:types>
    <xsd:schema targetNamespace="http://www.convertigo.com/convertigo/projects/template_FLEX"><xsd:include schemaLocation="template_FLEX.xsd"/></xsd:schema>
  </wsdl:types>
  <wsdl:portType name="template_FLEXPortType">
  </wsdl:portType>
  <wsdl:binding name="template_FLEXSOAPBinding" type="template_FLEX_ns:template_FLEXPortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
  </wsdl:binding>
  <wsdl:service name="template_FLEX">
    <wsdl:port name="template_FLEXSOAP" binding="template_FLEX_ns:template_FLEXSOAPBinding">
      <soap:address location="http://localhost:18080/convertigo/projects/template_FLEX/.wsl"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
