<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="template_javelinIntegration" targetNamespace="http://www.convertigo.com/convertigo/projects/template_javelinIntegration" xmlns:template_javelinIntegration_ns="http://www.convertigo.com/convertigo/projects/template_javelinIntegration" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/">
  <wsdl:types>
    <xsd:schema targetNamespace="http://www.convertigo.com/convertigo/projects/template_javelinIntegration"><xsd:include schemaLocation="template_javelinIntegration.xsd"/></xsd:schema>
  </wsdl:types>
  <wsdl:portType name="template_javelinIntegrationPortType">
  </wsdl:portType>
  <wsdl:binding name="template_javelinIntegrationSOAPBinding" type="template_javelinIntegration_ns:template_javelinIntegrationPortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
  </wsdl:binding>
  <wsdl:service name="template_javelinIntegration">
    <wsdl:port name="template_javelinIntegrationSOAP" binding="template_javelinIntegration_ns:template_javelinIntegrationSOAPBinding">
      <soap:address location="http://localhost:18080/convertigo/projects/template_javelinIntegration/.wsl"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
