<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="template_javelinIntegration" targetNamespace="http://www.convertigo.com/convertigo/projects/template_javelinIntegration" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:template_javelinIntegration_ns="http://www.convertigo.com/convertigo/projects/template_javelinIntegration">
  <wsdl:types>
    <xsd:schema targetNamespace="http://www.convertigo.com/convertigo/projects/template_javelinIntegration"><xsd:include schemaLocation="template_javelinIntegration.xsd"/></xsd:schema>
  </wsdl:types>
  <wsdl:message name="javelinIntegrationTemplateConnector__XMLizeResponse">
    <wsdl:part name="parameters" element="template_javelinIntegration_ns:javelinIntegrationTemplateConnector__XMLizeResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="javelinIntegrationTemplateConnector__XMLizeRequest">
    <wsdl:part name="parameters" element="template_javelinIntegration_ns:javelinIntegrationTemplateConnector__XMLize">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="template_javelinIntegrationPortType">
    <wsdl:operation name="javelinIntegrationTemplateConnector__XMLize">
<wsdl:documentation><![CDATA[]]></wsdl:documentation>
      <wsdl:input message="template_javelinIntegration_ns:javelinIntegrationTemplateConnector__XMLizeRequest">
    </wsdl:input>
      <wsdl:output message="template_javelinIntegration_ns:javelinIntegrationTemplateConnector__XMLizeResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="template_javelinIntegrationSOAPBinding" type="template_javelinIntegration_ns:template_javelinIntegrationPortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="javelinIntegrationTemplateConnector__XMLize">
<wsdl:documentation><![CDATA[]]></wsdl:documentation>
      <soap:operation soapAction="template_javelinIntegration?javelinIntegrationTemplateConnector__XMLize"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="template_javelinIntegration">
    <wsdl:port name="template_javelinIntegrationSOAP" binding="template_javelinIntegration_ns:template_javelinIntegrationSOAPBinding">
      <soap:address location="http://localhost:18080/convertigo/projects/template_javelinIntegration/.wsl"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
