<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="lib_Yammer" targetNamespace="http://www.convertigo.com/convertigo/projects/lib_Yammer" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:lib_Yammer_ns="http://www.convertigo.com/convertigo/projects/lib_Yammer">
  <wsdl:types>
    <xsd:schema targetNamespace="http://www.convertigo.com/convertigo/projects/lib_Yammer"><xsd:include schemaLocation="lib_Yammer.temp.xsd"/></xsd:schema>
  </wsdl:types>
  <wsdl:portType name="lib_YammerPortType">
  </wsdl:portType>
  <wsdl:portType name="lib_YammerPortType_RPC">
  </wsdl:portType>
  <wsdl:binding name="lib_YammerSOAPBinding_RPC" type="lib_Yammer_ns:lib_YammerPortType_RPC">
    <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
  </wsdl:binding>
  <wsdl:binding name="lib_YammerSOAPBinding" type="lib_Yammer_ns:lib_YammerPortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
  </wsdl:binding>
  <wsdl:service name="lib_Yammer">
    <wsdl:port name="lib_YammerSOAP_RPC" binding="lib_Yammer_ns:lib_YammerSOAPBinding_RPC">
      <soap:address location="http://localhost:18080/convertigo/projects/lib_Yammer/.ws"/>
    </wsdl:port>
    <wsdl:port name="lib_YammerSOAP" binding="lib_Yammer_ns:lib_YammerSOAPBinding">
      <soap:address location="http://localhost:18080/convertigo/projects/lib_Yammer/.wsl"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
