<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="sample_database_HSQLDB" targetNamespace="http://www.convertigo.com/convertigo/projects/sample_database_HSQLDB" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:sample_database_HSQLDB_ns="http://www.convertigo.com/convertigo/projects/sample_database_HSQLDB" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/">
  <wsdl:types>
    <xsd:schema targetNamespace="http://www.convertigo.com/convertigo/projects/sample_database_HSQLDB"><xsd:include schemaLocation="sample_database_HSQLDB.xsd"/></xsd:schema>
  </wsdl:types>
  <wsdl:portType name="sample_database_HSQLDBPortType">
  </wsdl:portType>
  <wsdl:binding name="sample_database_HSQLDBSOAPBinding" type="sample_database_HSQLDB_ns:sample_database_HSQLDBPortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
  </wsdl:binding>
  <wsdl:service name="sample_database_HSQLDB">
    <wsdl:port name="sample_database_HSQLDBSOAP" binding="sample_database_HSQLDB_ns:sample_database_HSQLDBSOAPBinding">
      <soap:address location="http://localhost:18080/convertigo/projects/sample_database_HSQLDB/.wsl"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
