<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="demo_usDirectory" targetNamespace="http://www.convertigo.com/convertigo/projects/demo_usDirectory" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:demo_usDirectory_ns="http://www.convertigo.com/convertigo/projects/demo_usDirectory" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:types>
    <xsd:schema targetNamespace="http://www.convertigo.com/convertigo/projects/demo_usDirectory"><xsd:include schemaLocation="demo_usDirectory.xsd"/></xsd:schema>
  </wsdl:types>
  <wsdl:portType name="demo_usDirectoryPortType">
  </wsdl:portType>
  <wsdl:binding name="demo_usDirectorySOAPBinding" type="demo_usDirectory_ns:demo_usDirectoryPortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
  </wsdl:binding>
  <wsdl:service name="demo_usDirectory">
    <wsdl:port name="demo_usDirectorySOAP" binding="demo_usDirectory_ns:demo_usDirectorySOAPBinding">
      <soap:address location="http://localhost:18080/convertigo/projects/demo_usDirectory/.wsl"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
