<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="template_sequence" targetNamespace="http://www.convertigo.com/convertigo/projects/template_sequence" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:template_sequence_ns="http://www.convertigo.com/convertigo/projects/template_sequence">
  <wsdl:types>
    <xsd:schema targetNamespace="http://www.convertigo.com/convertigo/projects/template_sequence"><xsd:include schemaLocation="template_sequence.xsd"/></xsd:schema>
  </wsdl:types>
  <wsdl:message name="void__DefaultTransactionResponse">
    <wsdl:part name="parameters" element="template_sequence_ns:void__DefaultTransactionResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="void__DefaultTransactionRequest">
    <wsdl:part name="parameters" element="template_sequence_ns:void__DefaultTransaction">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="template_sequencePortType">
    <wsdl:operation name="void__DefaultTransaction">
<wsdl:documentation><![CDATA[]]></wsdl:documentation>
      <wsdl:input message="template_sequence_ns:void__DefaultTransactionRequest">
    </wsdl:input>
      <wsdl:output message="template_sequence_ns:void__DefaultTransactionResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="template_sequenceSOAPBinding" type="template_sequence_ns:template_sequencePortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="void__DefaultTransaction">
<wsdl:documentation><![CDATA[]]></wsdl:documentation>
      <soap:operation soapAction="template_sequence?void__DefaultTransaction"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="template_sequence">
    <wsdl:port name="template_sequenceSOAP" binding="template_sequence_ns:template_sequenceSOAPBinding">
      <soap:address location="http://localhost:18080/convertigo/projects/template_sequence/.wsl"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
