<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="lib_LinkedIn" targetNamespace="http://www.convertigo.com/convertigo/projects/lib_LinkedIn" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:lib_LinkedIn_ns="http://www.convertigo.com/convertigo/projects/lib_LinkedIn">
  <wsdl:types>
    <xsd:schema targetNamespace="http://www.convertigo.com/convertigo/projects/lib_LinkedIn"><xsd:include schemaLocation="lib_LinkedIn.xsd"/></xsd:schema>
  </wsdl:types>
  <wsdl:portType name="lib_LinkedInPortType">
  </wsdl:portType>
  <wsdl:portType name="lib_LinkedInPortType_RPC">
  </wsdl:portType>
  <wsdl:binding name="lib_LinkedInSOAPBinding_RPC" type="lib_LinkedIn_ns:lib_LinkedInPortType_RPC">
    <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
  </wsdl:binding>
  <wsdl:binding name="lib_LinkedInSOAPBinding" type="lib_LinkedIn_ns:lib_LinkedInPortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
  </wsdl:binding>
  <wsdl:service name="lib_LinkedIn">
    <wsdl:port name="lib_LinkedInSOAP_RPC" binding="lib_LinkedIn_ns:lib_LinkedInSOAPBinding_RPC">
      <soap:address location="http://localhost:18080/convertigo/projects/lib_LinkedIn/.ws"/>
    </wsdl:port>
    <wsdl:port name="lib_LinkedInSOAP" binding="lib_LinkedIn_ns:lib_LinkedInSOAPBinding">
      <soap:address location="http://localhost:18080/convertigo/projects/lib_LinkedIn/.wsl"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
