<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="sample_database_XLS" targetNamespace="http://www.convertigo.com/convertigo/projects/sample_database_XLS" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:sample_database_XLS_ns="http://www.convertigo.com/convertigo/projects/sample_database_XLS" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:types>
    <xsd:schema targetNamespace="http://www.convertigo.com/convertigo/projects/sample_database_XLS"><xsd:include schemaLocation="sample_database_XLS.xsd"/></xsd:schema>
  </wsdl:types>
  <wsdl:message name="selectFromPeopleTableRequest">
    <wsdl:part name="parameters" element="sample_database_XLS_ns:selectFromPeopleTable">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="selectFromPeopleTableResponse">
    <wsdl:part name="parameters" element="sample_database_XLS_ns:selectFromPeopleTableResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="sample_database_XLSPortType">
    <wsdl:operation name="selectFromPeopleTable">
<wsdl:documentation><![CDATA[Sample sequence that computes the folder of the actual project + the xls folder into which is the file. The sequence takes the Excel file name as a variable so this name has to be updated also dynamically in the connection string. The connection string overrides the connector database URL, so the request is made in one of the two local Excel files.
]]></wsdl:documentation>
      <wsdl:input message="sample_database_XLS_ns:selectFromPeopleTableRequest">
    </wsdl:input>
      <wsdl:output message="sample_database_XLS_ns:selectFromPeopleTableResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="sample_database_XLSSOAPBinding" type="sample_database_XLS_ns:sample_database_XLSPortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="selectFromPeopleTable">
<wsdl:documentation><![CDATA[Sample sequence that computes the folder of the actual project + the xls folder into which is the file. The sequence takes the Excel file name as a variable so this name has to be updated also dynamically in the connection string. The connection string overrides the connector database URL, so the request is made in one of the two local Excel files.
]]></wsdl:documentation>
      <soap:operation soapAction="sample_database_XLS?selectFromPeopleTable"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="sample_database_XLS">
    <wsdl:port name="sample_database_XLSSOAP" binding="sample_database_XLS_ns:sample_database_XLSSOAPBinding">
      <soap:address location="http://localhost:18080/convertigo/projects/sample_database_XLS/.wsl"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
