<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="template_webIntegration" targetNamespace="http://www.convertigo.com/convertigo/projects/template_webIntegration" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:template_webIntegration_ns="http://www.convertigo.com/convertigo/projects/template_webIntegration" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/">
  <wsdl:types>
    <xsd:schema targetNamespace="http://www.convertigo.com/convertigo/projects/template_webIntegration"><xsd:include schemaLocation="template_webIntegration.xsd"/></xsd:schema>
  </wsdl:types>
  <wsdl:portType name="template_webIntegrationPortType">
  </wsdl:portType>
  <wsdl:binding name="template_webIntegrationSOAPBinding" type="template_webIntegration_ns:template_webIntegrationPortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
  </wsdl:binding>
  <wsdl:service name="template_webIntegration">
    <wsdl:port name="template_webIntegrationSOAP" binding="template_webIntegration_ns:template_webIntegrationSOAPBinding">
      <soap:address location="http://localhost:18080/convertigo/projects/template_webIntegration/.wsl"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
