<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="sample_documentation_CWC" targetNamespace="http://www.convertigo.com/convertigo/projects/sample_documentation_CWC" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:sample_documentation_CWC_ns="http://www.convertigo.com/convertigo/projects/sample_documentation_CWC" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/">
  <wsdl:types>
    <xsd:schema targetNamespace="http://www.convertigo.com/convertigo/projects/sample_documentation_CWC"><xsd:include schemaLocation="sample_documentation_CWC.xsd"/></xsd:schema>
  </wsdl:types>
  <wsdl:portType name="sample_documentation_CWCPortType">
  </wsdl:portType>
  <wsdl:binding name="sample_documentation_CWCSOAPBinding" type="sample_documentation_CWC_ns:sample_documentation_CWCPortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
  </wsdl:binding>
  <wsdl:service name="sample_documentation_CWC">
    <wsdl:port name="sample_documentation_CWCSOAP" binding="sample_documentation_CWC_ns:sample_documentation_CWCSOAPBinding">
      <soap:address location="http://localhost:18080/convertigo/projects/sample_documentation_CWC/.wsl"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
