<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="sampleMobileRssNYTimes" targetNamespace="http://www.convertigo.com/convertigo/projects/sampleMobileRssNYTimes" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:sampleMobileRssNYTimes_ns="http://www.convertigo.com/convertigo/projects/sampleMobileRssNYTimes" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:types>
    <xsd:schema targetNamespace="http://www.convertigo.com/convertigo/projects/sampleMobileRssNYTimes"><xsd:include schemaLocation="sampleMobileRssNYTimes.xsd"/></xsd:schema>
  </wsdl:types>
  <wsdl:message name="void__DefaultTransactionRequest">
    <wsdl:part name="parameters" element="sampleMobileRssNYTimes_ns:void__DefaultTransaction">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="void__DefaultTransactionResponse">
    <wsdl:part name="parameters" element="sampleMobileRssNYTimes_ns:void__DefaultTransactionResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="sampleMobileRssNYTimesPortType">
    <wsdl:operation name="void__DefaultTransaction">
<wsdl:documentation><![CDATA[]]></wsdl:documentation>
      <wsdl:input message="sampleMobileRssNYTimes_ns:void__DefaultTransactionRequest">
    </wsdl:input>
      <wsdl:output message="sampleMobileRssNYTimes_ns:void__DefaultTransactionResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="sampleMobileRssNYTimesSOAPBinding" type="sampleMobileRssNYTimes_ns:sampleMobileRssNYTimesPortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="void__DefaultTransaction">
<wsdl:documentation><![CDATA[]]></wsdl:documentation>
      <soap:operation soapAction="sampleMobileRssNYTimes?void__DefaultTransaction"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="sampleMobileRssNYTimes">
    <wsdl:port name="sampleMobileRssNYTimesSOAP" binding="sampleMobileRssNYTimes_ns:sampleMobileRssNYTimesSOAPBinding">
      <soap:address location="http://localhost:18080/convertigo/projects/sampleMobileRssNYTimes/.wsl"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
