<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="demo_SalesForce" targetNamespace="http://www.convertigo.com/convertigo/projects/demo_SalesForce" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:demo_SalesForce_ns="http://www.convertigo.com/convertigo/projects/demo_SalesForce" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/">
  <wsdl:types>
    <xsd:schema targetNamespace="http://www.convertigo.com/convertigo/projects/demo_SalesForce"><xsd:include schemaLocation="demo_SalesForce.xsd"/></xsd:schema>
  </wsdl:types>
  <wsdl:portType name="demo_SalesForcePortType">
  </wsdl:portType>
  <wsdl:binding name="demo_SalesForceSOAPBinding" type="demo_SalesForce_ns:demo_SalesForcePortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
  </wsdl:binding>
  <wsdl:service name="demo_SalesForce">
    <wsdl:port name="demo_SalesForceSOAP" binding="demo_SalesForce_ns:demo_SalesForceSOAPBinding">
      <soap:address location="http://localhost:18080/convertigo/projects/demo_SalesForce/.wsl"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
