<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="sample_refManual_siteClipper" targetNamespace="http://www.convertigo.com/convertigo/projects/sample_refManual_siteClipper" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:sample_refManual_siteClipper_ns="http://www.convertigo.com/convertigo/projects/sample_refManual_siteClipper" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/">
  <wsdl:types>
    <xsd:schema targetNamespace="http://www.convertigo.com/convertigo/projects/sample_refManual_siteClipper"><xsd:include schemaLocation="sample_refManual_siteClipper.xsd"/></xsd:schema>
  </wsdl:types>
  <wsdl:portType name="sample_refManual_siteClipperPortType">
  </wsdl:portType>
  <wsdl:binding name="sample_refManual_siteClipperSOAPBinding" type="sample_refManual_siteClipper_ns:sample_refManual_siteClipperPortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
  </wsdl:binding>
  <wsdl:service name="sample_refManual_siteClipper">
    <wsdl:port name="sample_refManual_siteClipperSOAP" binding="sample_refManual_siteClipper_ns:sample_refManual_siteClipperSOAPBinding">
      <soap:address location="http://localhost:18080/convertigo/projects/sample_refManual_siteClipper/.wsl"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
