<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="template_siteClipper" targetNamespace="http://www.convertigo.com/convertigo/projects/template_siteClipper" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:template_siteClipper_ns="http://www.convertigo.com/convertigo/projects/template_siteClipper" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:types>
    <xsd:schema targetNamespace="http://www.convertigo.com/convertigo/projects/template_siteClipper"><xsd:include schemaLocation="template_siteClipper.xsd"/></xsd:schema>
  </wsdl:types>
  <wsdl:portType name="template_siteClipperPortType_RPC">
  </wsdl:portType>
  <wsdl:portType name="template_siteClipperPortType">
  </wsdl:portType>
  <wsdl:binding name="template_siteClipperSOAPBinding" type="template_siteClipper_ns:template_siteClipperPortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
  </wsdl:binding>
  <wsdl:binding name="template_siteClipperSOAPBinding_RPC" type="template_siteClipper_ns:template_siteClipperPortType_RPC">
    <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
  </wsdl:binding>
  <wsdl:service name="template_siteClipper">
    <wsdl:port name="template_siteClipperSOAP" binding="template_siteClipper_ns:template_siteClipperSOAPBinding">
      <soap:address location="http://localhost:18080/convertigo/projects/template_siteClipper/.wsl"/>
    </wsdl:port>
    <wsdl:port name="template_siteClipperSOAP_RPC" binding="template_siteClipper_ns:template_siteClipperSOAPBinding_RPC">
      <soap:address location="http://localhost:18080/convertigo/projects/template_siteClipper/.ws"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
