<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="template_CICS" targetNamespace="http://www.convertigo.com/convertigo/projects/template_CICS" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:template_CICS_ns="http://www.convertigo.com/convertigo/projects/template_CICS" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/">
  <wsdl:types>
    <xsd:schema targetNamespace="http://www.convertigo.com/convertigo/projects/template_CICS"><xsd:include schemaLocation="template_CICS.xsd"/></xsd:schema>
  </wsdl:types>
  <wsdl:portType name="template_CICSPortType">
  </wsdl:portType>
  <wsdl:binding name="template_CICSSOAPBinding" type="template_CICS_ns:template_CICSPortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
  </wsdl:binding>
  <wsdl:service name="template_CICS">
    <wsdl:port name="template_CICSSOAP" binding="template_CICS_ns:template_CICSSOAPBinding">
      <soap:address location="http://localhost:18080/convertigo/projects/template_CICS/.wsl"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
