<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="template_SQL_jQueryWeb" targetNamespace="http://www.convertigo.com/convertigo/projects/template_SQL_jQueryWeb" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:template_SQL_jQueryWeb_ns="http://www.convertigo.com/convertigo/projects/template_SQL_jQueryWeb" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:types>
    <xsd:schema targetNamespace="http://www.convertigo.com/convertigo/projects/template_SQL_jQueryWeb"><xsd:include schemaLocation="template_SQL_jQueryWeb.xsd"/></xsd:schema>
  </wsdl:types>
  <wsdl:message name="checkEmailResponse">
    <wsdl:part name="parameters" element="template_SQL_jQueryWeb_ns:checkEmailResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="checkEmailRequest">
    <wsdl:part name="parameters" element="template_SQL_jQueryWeb_ns:checkEmail">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="template_SQL_jQueryWebPortType">
    <wsdl:operation name="checkEmail">
<wsdl:documentation/>
      <wsdl:input message="template_SQL_jQueryWeb_ns:checkEmailRequest">
    </wsdl:input>
      <wsdl:output message="template_SQL_jQueryWeb_ns:checkEmailResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="template_SQL_jQueryWebSOAPBinding" type="template_SQL_jQueryWeb_ns:template_SQL_jQueryWebPortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="checkEmail">
<wsdl:documentation/>
      <soap:operation soapAction="template_SQL_jQueryWeb?checkEmail"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="template_SQL_jQueryWeb">
    <wsdl:port name="template_SQL_jQueryWebSOAP" binding="template_SQL_jQueryWeb_ns:template_SQL_jQueryWebSOAPBinding">
      <soap:address location="http://localhost:18080/convertigo/projects/template_SQL_jQueryWeb/.wsl"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
