<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="demo_legacyCRM" targetNamespace="http://www.convertigo.com/convertigo/projects/demo_legacyCRM" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:demo_legacyCRM_ns="http://www.convertigo.com/convertigo/projects/demo_legacyCRM" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/">
  <wsdl:types>
    <xsd:schema targetNamespace="http://www.convertigo.com/convertigo/projects/demo_legacyCRM"><xsd:include schemaLocation="demo_legacyCRM.xsd"/></xsd:schema>
  </wsdl:types>
  <wsdl:portType name="demo_legacyCRMPortType">
  </wsdl:portType>
  <wsdl:binding name="demo_legacyCRMSOAPBinding" type="demo_legacyCRM_ns:demo_legacyCRMPortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
  </wsdl:binding>
  <wsdl:service name="demo_legacyCRM">
    <wsdl:port name="demo_legacyCRMSOAP" binding="demo_legacyCRM_ns:demo_legacyCRMSOAPBinding">
      <soap:address location="http://localhost:18080/convertigo/projects/demo_legacyCRM/.wsl"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
