<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="lib_GoogleSpreadsheets" targetNamespace="http://www.convertigo.com/convertigo/projects/lib_GoogleSpreadsheets" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:lib_GoogleSpreadsheets_ns="http://www.convertigo.com/convertigo/projects/lib_GoogleSpreadsheets" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/">
  <wsdl:types>
    <xsd:schema targetNamespace="http://www.convertigo.com/convertigo/projects/lib_GoogleSpreadsheets"><xsd:include schemaLocation="lib_GoogleSpreadsheets.xsd"/>
  	</xsd:schema>
  </wsdl:types>
  <wsdl:portType name="lib_GoogleSpreadsheetsPortType">
  </wsdl:portType>
  <wsdl:binding name="lib_GoogleSpreadsheetsSOAPBinding" type="lib_GoogleSpreadsheets_ns:lib_GoogleSpreadsheetsPortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
  </wsdl:binding>
  <wsdl:service name="lib_GoogleSpreadsheets">
    <wsdl:port name="lib_GoogleSpreadsheetsSOAP" binding="lib_GoogleSpreadsheets_ns:lib_GoogleSpreadsheetsSOAPBinding">
      <soap:address location="http://localhost:18080/convertigo/projects/lib_GoogleSpreadsheets/.wsl"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
